[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/=lib/openzeppelin-contracts/"]
gas_limit = "50000000"
solc_version = "0.8.23"
optimizer = true
optimizer_runs = 1000000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
